defaults:
  - model: "timm"

inference:
  batch_size: 32
  model_weights: checkpoints/classification/model_epoch_3_jsn_accuracy_0.6577952000684419_erosion_accuracy_0.4469667149202592.pth
  bbox_csv: data/eval_detection_output/bbox_txts/all_bboxes.txt
  image_dir: data/eval_cropped_images
  output_csv: submit.csv
  device: "cuda:0"