# Model configuration
random_state: 43
defaults:
  - model: timm
  - optimizer: adamw
  - train_dataset: base_ds
  - val_dataset: base_ds
  - scheduler: step_lr

# Training configuration
training:
  normalized_jsn_class_weights: [0.363, 0.624, 0.272, 0.575, 3.827]
  normalized_erosion_class_weights: [0.012, 0.183, 0.391, 2.571, 7.714, 1.058]
  num_workers: 4
  epochs: 10
  batch_size: 16
  save_dir: "/kaggle/working/checkpoints/classification"  

# WandB configuration
wandb:
  api_key: ""
  project: "ARISE-2025"